GET http://localhost:5057/posts

###
POST http://localhost:5057/posts
Content-Type: application/json

{
    "Title": "Devin AI",
    "Content" : "Would Devin be the end of Software Engineers"
}

###
GET http://localhost:5057/comments

###
POST http://localhost:5057/comments
Content-Type: application/json

{
    "Comment" : "Why Software Engineering so Hard??"
}
