// <auto-generated />
using BlogProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogProject.Data.Migrations
{
    [DbContext(typeof(VideoInfoContext))]
    partial class VideoInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BlogProject.Entities.VideoInfo", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("VideoId");

                    b.ToTable("VideoInfos");

                    b.HasData(
                        new
                        {
                            VideoId = 1,
                            VideoUrl = "https://www.youtube.com/watch?v=iDQAZEJK8lI&list=PLoILbKo9rG3skRCj37Kn5Zj803hhiuRK6"
                        },
                        new
                        {
                            VideoId = 2,
                            VideoUrl = "https://www.youtube.com/watch?v=GCraGHx6gso"
                        },
                        new
                        {
                            VideoId = 3,
                            VideoUrl = "https://www.youtube.com/watch?v=NwaabHqPHeM"
                        },
                        new
                        {
                            VideoId = 4,
                            VideoUrl = "https://www.youtube.com/watch?v=tK9Oc6AEnR4"
                        },
                        new
                        {
                            VideoId = 5,
                            VideoUrl = "https://www.youtube.com/watch?v=6gwF8mG3UUY"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
